### PR TITLE
Use `addons-scanner-utils` for IO stuff

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://github.com/mozilla/addons-linter/issues/2866

---

This patch uses the `addons-scanner-utils` (used by other scanners) for the IO layer. There is no other change than that (the `autoClose` feature will be implemented in a follow-up patch).

### CODE REVIEW

**Comment by rpl** [comment]
> @rpl FYI, this is needed to hopefully improve the linter execution speed (by disabling an obscure "auto-close" feature that I will describe in a new issue soon). The code in `addons-scanner-utils` is very similar to the code currently living in this project `src/io/`, but it has been rewritten with TypeScript. We're using it in other scanners so it should be fine.

nice! I like the idea of sharing that code instead of having multiple implementations and having to keep them in sync when we do fix bugs or enhance them.

@willdurand I just gave a quick look to the changes in the PR, but I was wondering: would it be reasonable to keep one integration test that runs the linter on a sample of the fixtures (e.g. one crx3, one xpi or zip file and a directory with an unpacked extension) being removed and confirm that we get the expected results?
just as a smoke test to make it easier to catch potential regressions when we do update the new dependency.

**Comment by willdurand** [comment]
> @willdurand I just gave a quick look to the changes in the PR, but I was wondering: would it be reasonable to keep one integration test that runs the linter on a sample of the fixtures (e.g. one crx3, one xpi or zip file and a directory with an unpacked extension) being removed and confirm that we get the expected results?
> just as a smoke test to make it easier to catch potential regressions when we do update the new dependency.

I thought we had that already, no? We have a bunch of tests reading fixture files.

**Comment by rpl** [comment]
> I thought we had that already, no? We have a bunch of tests reading fixture files.

Honestly I haven't checked yet if we do have enough coverage already, I was just pointing it out as something that may be worth to double-check explicitly.

I'll give it a look asap.

**Comment by willdurand** [comment]
> Honestly I haven't checked yet if we do have enough coverage already, I was just pointing it out as something that may be worth to double-check explicitly.
> 
> I'll give it a look asap.

Thanks. `xpi` files and directories are well-covered I think (given the variety of fixtures). Maybe we should add one test for `crx` files, though.

**Review by diox — APPROVED** [review]
I'll leave to @rpl to decide if this needs more integration tests to be sure but r+ from me

**Comment by rpl** [comment]
> I'll leave to @rpl to decide if this needs more integration tests to be sure but r+ from me

we discussed about this in the triage meeting today, we agreed to just add coverage for a crx file (at least one crx3 file) and then proceed with merging this as already accepted by diox.

I'll be happy to take a look if Will feels that it would be necessary, otherwise I will just review the follow up PR #3429 on marked as ready for a review.

**Pull request merged**
