### PR TITLE
Update firefox 58 schema import.

### PR DESCRIPTION
**Pull request by EnTeQuAk**

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
meh, I forgot about tests. I'll update those tomorrow morning and cherry-pick them into the tag

**Comment by mstriemer** [comment]
I sorted everything out with the 59 import, should be a patch up very soon for that. We might be able to use that instead.

**Comment by mstriemer** [comment]
The 59 schema import is in #1798. I removed any updates to the download part of firefox-schema-import.js so these changes can land instead of the ones I made locally.

**Comment by EnTeQuAk** [comment]
Closing for now, I'll resubmit this with the mozilla-unified part only.

**Pull request closed without merging**
