### PR TITLE
Decode pathname

### PR DESCRIPTION
**Pull request by asamuzaK**
Follow up for #1730

This PR includes
* decode URI pathname.
* add tests for normalizePath() function.

### CODE REVIEW

**Comment by caitmuenster** [comment]
Thanks @asamuzaK! Would you be interested in creating a profile on [mozillians.org](https://mozillians.org)? I'd love to vouch for your contributions to AMO. :)

**Comment by asamuzaK** [comment]
@caitmuenster 
Created.
https://mozillians.org/ja/u/asamuzaK/

**Comment by asamuzaK** [comment]
@caitmuenster 
Well, my nickname is wrong. :)
Not asamu*s*aK but asamu*z*aK.
It is one that turned over my first name.

[Mozillians: Kazumasa Hasegawa](https://mozillians.org/ja/u/asamuzaK/ "Mozillians: Kazumasa Hasegawa")
[Add-ons/Contribute/Recognition - MozillaWiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition "Add-ons/Contribute/Recognition - MozillaWiki")

**Comment by caitmuenster** [comment]
Oh no, I am so sorry @asamuzaK! I can update the recognition wiki but unfortunately I can't edit the vouch. :( This was completely my oversight and I am really sorry for messing this up.

**Comment by asamuzaK** [comment]
That's okay, never mind! :)

**Pull request merged**
