### PR TITLE
Remove eslint-plugin-jest

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://github.com/mozilla/addons-linter/issues/3381

### CODE REVIEW

**Review by wagnerand — COMMENTED** [review]
I'm wondering why [`cec0c7a` (#3318)](https://github.com/mozilla/addons-linter/pull/3318/commits/cec0c7a305c99fa85ef53885a58d75a5f7e72c1e) failed with

```
/home/travis/build/mozilla/addons-linter/tests/unit/schema/test.firefox-schemas-import.js
  58:5  error  'pending' is not defined  no-undef
```

but [`7a9a7ca` (#3327)](https://github.com/mozilla/addons-linter/pull/3327/commits/7a9a7ca88ba04f82336308616fab92cd4e714055) didn't. I believe it should have.

**Comment by willdurand** [comment]
> I'm wondering why [`cec0c7a` (#3318)](https://github.com/mozilla/addons-linter/pull/3318/commits/cec0c7a305c99fa85ef53885a58d75a5f7e72c1e) failed with
> 
> ```
> /home/travis/build/mozilla/addons-linter/tests/unit/schema/test.firefox-schemas-import.js
>   58:5  error  'pending' is not defined  no-undef
> ```
> 
> but [`7a9a7ca` (#3327)](https://github.com/mozilla/addons-linter/pull/3327/commits/7a9a7ca88ba04f82336308616fab92cd4e714055) didn't. I believe it should have.

ESLint error from 2 weeks ago? I don't know. This rule isn't related to the jest plugin, though, so 🤷

**Comment by wagnerand** [comment]
> > I'm wondering why [`cec0c7a` (#3318)](https://github.com/mozilla/addons-linter/pull/3318/commits/cec0c7a305c99fa85ef53885a58d75a5f7e72c1e) failed with
> > ```
> > /home/travis/build/mozilla/addons-linter/tests/unit/schema/test.firefox-schemas-import.js
> >   58:5  error  'pending' is not defined  no-undef
> > ```
> > 
> > 
> > but [`7a9a7ca` (#3327)](https://github.com/mozilla/addons-linter/pull/3327/commits/7a9a7ca88ba04f82336308616fab92cd4e714055) didn't. I believe it should have.
> 
> ESLint error from 2 weeks ago? I don't know. This rule isn't related to the jest plugin, though, so 🤷

Hm, but the error only threw in the error that updated eslint-plugin-jest from 23 to 24, which the eslint-config-amo PR already had.

**Comment by willdurand** [comment]
That could be because the AMO config didn't require the same ESLint version as the jest plugin in version 24 or something. That's why we need to remove that lib from the list of dependencies.

**Comment by wagnerand** [comment]
I still don't understand exactly the difference in test behavior but ok. Since https://github.com/mozilla/addons-linter/blob/master/tests/unit/schema/test.firefox-schemas-import.js#L25 doesn't seem to be needed anymore (despite the explicit failure when updating to 24), can you remove that line?

**Comment by willdurand** [comment]
> can you remove that line?

that's for another patch I believe. This is about removing a dependency.

**Comment by wagnerand** [comment]
That line was just added to make the tests pass for the dependency we are removing.

**Comment by rpl** [comment]
> That line was just added to make the tests pass for the dependency we are removing.

The `no-undef` linting error is actually detected if you comment out that line after applying this change and refreshing node_modules using `npm ci`, that change is here to stay ;-)

I didn't dig too much into it, but I think that the previous behavior mismatch may have been likely triggered by having two different version of the eslint-plugin-jest in the dependencies (one as a direct dependency and one as a dependency of eslint-config-amo).

**Review by rpl — APPROVED** [review]

**Comment by wagnerand** [comment]
> The `no-undef` linting error is actually detected if you comment out that line after applying this change and refreshing node_modules using `npm ci`, that change is here to stay ;-)

I did that and tests still passed for me.

**Comment by wagnerand** [comment]
Weird, I can reproduce the behavior now.

**Review by wagnerand — APPROVED** [review]

**Comment by willdurand** [comment]
thanks!

**Pull request merged**
