### PR TITLE
error for missing messages.json in language directory

### LINKED ISSUE #1585: No error or warning displayed when the extension has an empty language directory
### Describe the problem and steps to reproduce it:
1. Create an internationalized extension
2. Create an empty language directory in the _locales folder

### What happened?
The linter didn’t say anything.

### What did you expect to happen?
The linter should display an error that the empty language directory is missing the required messages.json file.

### Anything else we should know?
Firefox refuses to load extensions that have a language directory that is missing the required messages.json file.

### PR DESCRIPTION
**Pull request by pardeepshokeen**
* [x]  Fixes #1585 at the top of your PR.
* [ ] Add a description of the the changes introduced in this PR.
* [x] The change has been successfully run locally.
* [x] Add tests to cover the changes added in this PR.

### CODE REVIEW

**Comment by pardeepshokeen** [comment]
hi @EnTeQuAk .  I think you missed this PR. Would you please review this.

**Comment by caitmuenster** [comment]
Thanks, @pardeepshokeen! This contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#December_2017). 

Would you be interested in creating a profile on [mozillians.org](https://mozillians.org)? I'd be happy to vouch for your contribution. 

Welcome onboard! I look forward to seeing you around.

**Comment by pardeepshokeen** [comment]
hi @caitmuenster  . I have registered to mozillians.org.  My link is  https://mozillians.org/en-GB/u/pardeepshokeen/

**Comment by caitmuenster** [comment]
Thanks @pardeepshokeen! You're vouched. :)

**Pull request merged**
