### PR TITLE
Usage of 'mozIndexedDB' should be a warning instead of an error

### LINKED ISSUE #796: The use of mozIndexedDB should not be an error but a warning
Libraries and frameworks still use mozIndexedDB when assessing what's available in the browser, even https://github.com/mozilla/localForage/. The rules doc also says this should be a warning, but it is currently an error which for example, makes it impossible to submit webextensions that use localForage.

### PR DESCRIPTION
**Pull request by wagnerand**
Fixes #796

### CODE REVIEW

**Comment by tofumatt** [comment]
Please update `docs/rules.md` to clarify that this is now a warning and not an error.

r+wc

**Comment by wagnerand** [comment]
I get some (seemlingly) unrelated test failures, let's wait for travis...

**Comment by wagnerand** [comment]
Afaics, the rules document is correct, just the implementation was wrong.

**Comment by tofumatt** [comment]
Right on. A nitpick would be to change the rule from "not allowed" to "discouraged".

**Comment by wagnerand** [comment]
I am totally at loss about the test failures. Could you give me a hint?

Also, I don't see where it says "not allowed".

**Comment by wagnerand** [comment]
Ok, I updated the rule description.

**Comment by tofumatt** [comment]
After reviewing this and the tests failures this is r- (not safe to merge) until #798 is fixed. After that it's r+ but I'll have a look at making sure it's all okay and merge it in myself 👍

**Pull request closed without merging**
