### PR TITLE
remove the rdf scanner and old extension support

### LINKED ISSUE #424: Detect when a package is in a nested directory.
It's easy to package a dir which might result in things like manifest.json being under a directory in the package rather than being at the top level. We should flag that.

### LINKED ISSUE #464: Switch to a proper rdf parser
We only need to parse install.rdf file for dictionaries and langpacks but it would be a good idea to use a better parser.

### PR DESCRIPTION
**Pull request by andymckay**
* supports #1063, but I think there's a bit more clean up to do
* if there's no manifest.json it just throws that as an error
* removes the RDF parser, I don't think its used anywhere else

screenshot 2017-05-25 16 51 03

.. maybe also fixes #424 and we can close #464

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
I don't want to be a party pooper but afaik we eventually wanted to move language-pack and theme support from the validator over to the linter given that their support might last quite a bit longer? So we'd still need a rdf parser I think.

**Comment by tofumatt** [comment]
Yeah, it's likely worth keeping RDF support intact, though we probably want to trim down our usage of it for WebExtensions. Maybe we can use some of the code from this patch for that?

**Comment by andymckay** [comment]
Maybe: https://bugzilla.mozilla.org/show_bug.cgi?id=1365709 is about converting to a new webextension format language pack. I admit I don't know about timelines though.

Themes are just going to be webextensions too, heavy weight themes are dead in 57.

**Comment by jvillalobos** [comment]
There are also dictionaries, which also use `install.rdf`.

**Comment by andymckay** [comment]
So you want me to leave the RDF parser there, but just make linter.js just fail and say clearly no manifest.json rather than trying to guess what to do if one isn't present?

**Comment by tofumatt** [comment]
> So you want me to leave the RDF parser there, but just make linter.js just fail and say clearly no manifest.json rather than trying to guess what to do if one isn't present?

I think that makes the most sense for now. When we add support for other add-on types we can still use the RDF parser that way...

**Comment by andymckay** [comment]
Rightio, will do.

**Comment by muffinresearch** [comment]
fwiw (and feel free to correct me if I'm missing something) but I don't see the need to worry too much about removing the RDF parser if it's not being used in the linter today. If we want it back it's in history. It might benefit from re-implementing when we have solid use-case to use it for too.

**Comment by andymckay** [comment]
Going to step back from this back until the path is clearer.

**Comment by hameleonka** [comment]
I'll take this

**Pull request closed without merging**
