### PR TITLE
Remove Unused Dependency

### PR DESCRIPTION
**Pull request by sanAkdam**

### CODE REVIEW

**Comment by tofumatt** [comment]
Thanks for the PR! 👍

**Comment by sanAkdam** [comment]
oke, you are welcome 👍

**Comment by caitmuenster** [comment]
Thanks so much, San, and welcome onboard! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#November_2016). Happy hacking!

**Comment by sanAkdam** [comment]
it is my Pleasure 👍

On Nov 23, 2016 2:59 AM, "Caitlin Neiman" <notifications@github.com> wrote:
>
> Thanks so much, San, and welcome onboard! Your contribution has been
added to our recognition wiki. Happy hacking!

**Comment by pdehaan** [comment]
Ref #691

**Pull request merged**
