### PR TITLE
update dispensary to 0.10.1

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by tofumatt** [comment]
Already merged the greenkeeper PRs and they covered this. Cheers!

**Comment by groovecoder** [comment]
Ah, cool. /me checks out greenkeeper.

**Comment by groovecoder** [comment]
Can we get a release on this module too? Hoping to get the latest addons-linter + dispensary into shield-studies-addon-template ASAP.

**Comment by tofumatt** [comment]
Done: https://github.com/mozilla/addons-linter/releases/tag/0.15.8

**Comment by tofumatt** [comment]
It’s the best!

**Pull request closed without merging**
