### PR TITLE
fix(package): update fluent to version 0.6.3

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Closes #1800

### CODE REVIEW

**Comment by wagnerand** [comment]
@EnTeQuAk Looks like we can't upgrade to fluent 0.6 for now since it requires at least node 8.9.

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk Looks like we can't upgrade to fluent 0.4.2 or higher for now since it requires at least node 8.9 (projectfluent/fluent.js#95).

Indeed, but according to https://github.com/mozilla/addons-linter/issues/1789 we might want to use a different package long-term anyway. So it might make sense to look into that at some point.

**Comment by wagnerand** [comment]
Ok, but that same PR drops node 6 support for `fluent-syntax` as well. So, as long as we are still supporting node 6, I'm not sure it's worth the effort to migrate from one outdated package version to another.

**Comment by EnTeQuAk** [comment]
> Ok, but that same PR drops node 6 support for fluent-syntax as well. So, as long as we are still supporting node 6, I'm not sure it's worth the effort to migrate from one outdated package version to another.

Jupp, I don't think it is. :panda_face: We might drop node6 support once it's maintenance LTS window starts in April in coordination with what web-ext does but definitely not before that.

**Pull request closed without merging**
