### PR TITLE
Replace setupTestFrameworkScriptFile with setupFilesAfterEnv

### LINKED ISSUE #2515: Update jest config (setupTestFrameworkScriptFile is deprecated)
```
● Deprecation Warning:

  Option "setupTestFrameworkScriptFile" was replaced by configuration "setupFilesAfterEnv", which supports multiple paths.

  Please update your configuration.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

### PR DESCRIPTION
**Pull request by arku**
#### Checklist
- [x] This PR relates to an existing open issue and there are no existing PRs open for the same issue.
- [x] Add a description of the changes introduced in this PR.
- [x] The change has been successfully run locally.

Fixes #2515

Updates Jest config to fix the following deprecation warning:

```
  Option "setupTestFrameworkScriptFile" was replaced by configuration "setupFilesAfterEnv", which supports multiple paths.
```

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Thank you so much for your contribution!

**Comment by caitmuenster** [comment]
Woohoo, congrats on landing this patch, @arku! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Would you be interested in creating a profile on mozillians.org? I'd be happy to vouch for you!

**Comment by arku** [comment]
@caitmuenster Thanks!

Here's my [Mozillian profile](https://mozillians.org/en-US/u/arku).

**Comment by caitmuenster** [comment]
@arku your profile has been vouched! Thanks again for the patch and welcome onboard. We look forward to seeing you around the project! 🎉

**Pull request merged**
