### PR TITLE
Added build-locales script

### PR DESCRIPTION
**Pull request by ravneette**
In Reference to #1535

This PR adds the build-locales script in the bin folder to create js files from po files.
Might have merge conflicts with https://github.com/mozilla/addons-linter/pull/1702

### CODE REVIEW

**Comment by ravneette** [comment]
This should work once https://github.com/mozilla/addons-linter/pull/1702 is merged. Since I've committed the config file over there, I haven't added it over here to avoid duplication. 
That's why it might fail right now,.

**Comment by EnTeQuAk** [comment]
#1702 just got merged, mind updating this PR then?

**Comment by ravneette** [comment]
Hey @EnTeQuAk 

When I test this locally I get 
```
● Test suite failed to run

    EISDIR: illegal operation on a directory, read
        at Error (native)
      
      at Object.readSync (node_modules/jest-cli/node_modules/graceful-fs/polyfills.js:138:28)

```

Can you point me to the right direction?
This is the only error for all three of my open PR's.

**Comment by EnTeQuAk** [comment]
Sorry for the hiccup and weird test breakage, https://github.com/mozilla/addons-linter/pull/1749 just got merged and once you rebase your branch to master tests should be working fine again :)

**Comment by EnTeQuAk** [comment]
@ravneette hey, how is it going? Mind merging in master into this PR so that we can land this?

**Comment by ravneette** [comment]
Hey
Sorry about that. Not sure how I missed that comment ^. Bringing up to date now

**Comment by EnTeQuAk** [comment]
Thanks for the rebase and update, just merged it.

**Pull request merged**
