### PR TITLE
fixes #1590 for scripts/css files declared in manifest.json

### LINKED ISSUE #1590: Error should be displayed in case script is missing from the content_script folder.
### Describe the problem and steps to reproduce it:
Remove the script from content_script folder of any web extension and try to run it in Firefox. 

### What happened?
Web extension did not work properly

### What did you expect to happen?
A error message notifying that the Script is missing.

### Anything else we should know?
Error should be displayed in case script is missing from the content_script folder, or even if the content_script folder is missing.

### PR DESCRIPTION
**Pull request by hameleonka**
adds existence validation for scripts and css files declared in manifest.json under content_scripts

### CODE REVIEW

**Comment by hameleonka** [comment]
There is a (second)[https://github.com/mozilla/addons-linter/issues/1590#issuecomment-340224725] case should it be implemented in this PR?

**Comment by EnTeQuAk** [comment]
> There is a second case should it be implemented in this PR?

Let's open a separate issue about that and think / work on the 2nd part in another pull request if possible. That'll help keep things reviewable and fast-pacing :)

**Comment by caitmuenster** [comment]
Hey there, @hameleonka, would you like to create an account on [mozillians.org](https://mozillians.org)? We'd be happy to vouch for your contributions. :)

**Comment by hameleonka** [comment]
@caitmuenster thanks for the offer! I registered and here is my link https://mozillians.org/en-US/u/hameleonka/

**Pull request merged**
