### PR TITLE
fix #764 #863: ASCII in TOOLKIT_VERSION_REGEX

### LINKED ISSUE #764: Beta string versions should be allowed
@raphaelfaria previously filed this bug here: mozilla/web-extension-manifest-schema#144

The schema currently supports only integer numbers on version parts and prevents the signing of beta versions of web extensions.
It should allow this match `(a|alpha|b|beta|pre|rc)\d*$` at the last version part as described in: https://developer.mozilla.org/en-US/docs/Toolkit_version_format and https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Maintenance

### PR DESCRIPTION
**Pull request by groovecoder**
Update TOOLKIT_VERSION_REGEX to allow all ASCII characters in the
parts.

### CODE REVIEW

**Comment by groovecoder** [comment]
Hmm ... does anyone know why we have logic for each version `part < 0 || part > 65535` ?

**Comment by tofumatt** [comment]
Looks like this is missing some test coverage, can you run `npm test` locally and make sure there are zero uncovered lines?

**Comment by groovecoder** [comment]
Trying to fix ...

**Comment by groovecoder** [comment]
Coverage is back up to 100% and the regex is tighter now.

**Comment by tofumatt** [comment]
Not sure about the different part logic but this seems good to me. Feel free to file that as a question though and I can look into it 😀

Thanks for the PR!

**Comment by tofumatt** [comment]
r+

**Comment by groovecoder** [comment]
Thanks. How often does addons-linter make releases to npm?

**Comment by tofumatt** [comment]
There's no set schedule, it usually accompanies features and often AMO's
weekly Tuesday push. I'll see this gets released for this weeks push :-)

- tofumatt

**Comment by groovecoder** [comment]
Cool, thanks. I'll check about updating a web-ext release to use this new addons-linter release, and then I'll bring it all back to setting up continuous deployment for my add-on.

rabbithole

**Pull request merged**
