### PR TITLE
Drop tests on node4

### PR DESCRIPTION
**Pull request by wagnerand**
```
<TheOne> muffinresearch: have you folks talked about dropping tests on node4, now that node6 has been on LTS for a while? Tests on node4 take significantly longer
<@muffinresearch> yeah we already have elsewhere
<@muffinresearch> So feel free to do that anywhere that needs it.
```

### CODE REVIEW

**Comment by muffinresearch** [comment]
@wagnerand before we land this would be good to check that web-ext isn't relying on node4.

**Comment by muffinresearch** [comment]
See https://github.com/mozilla/web-ext#installation-from-source

**Comment by wagnerand** [comment]
Hm, both `dispensary` and `web-ext` tests pass on node 6. Is that enough?

**Comment by muffinresearch** [comment]
> Hm, both dispensary and web-ext tests pass on node 6. Is that enough?

If web-ext says it supports node 4 and then the linter doesn't we could break them. So I think before going ahead, it would be good to look at getting web-ext updated to support a similar policy of node 6+ support.

**Comment by wagnerand** [comment]
Ah, got it.

**Pull request merged**
