### PR TITLE
Revert "chore(package): update yargs to version 6.3.0"

### LINKED ISSUE #1023: web-ext lint error: Too many non-option arguments: got 1, maximum of 0
### Describe the problem and steps to reproduce it:

To reproduce:
- upgrade the `addons-linter` dependency of `web-ext` to `0.15.7` (or higher)
- run `npm install` and `npm run build` to get a new `web-ext`
- cd into any add-on
- type `web-ext lint`
### What happened?

It shows a usage message with this error:

```
Too many non-option arguments: got 1, maximum of 0
```
### What did you expect to happen?

The command should show a lint report
### Anything else we should know?

`web-ext` simulates passing a directory of source as the first command line argument to `addons-linter` [like this](https://github.com/mozilla/web-ext/blob/master/src/cmd/lint.js#L75). Maybe something changed? I don't see anything obvious at a glance.

The mystery saga of https://github.com/mozilla/addons-linter/issues/969 continues! It was definitely fixed but now it's broken again. See https://github.com/mozilla/web-ext/pull/606 and https://github.com/mozilla/web-ext/pull/616

### PR DESCRIPTION
**Pull request by tofumatt**
This reverts commit 07d23c2c53ba0ea089a2f7d8836ca020b4a315a9.

Fixes #1023

### CODE REVIEW

**Comment by tofumatt** [comment]
No worries. I think it has something to do with yargs across multiple apps that use it... we've had tests passing and things working here but `web-ext` getting weird output before.

We may want a test that includes `addons-linter` as `web-ext` does in the future to protect against upstream breakage.

**Comment by muffinresearch** [comment]
Since web-ext has a failing test, have you tried running the linter with a downgraded yargs in web-ext and seeing if their tests start passing?

**Comment by muffinresearch** [comment]
> Since web-ext has a failing test, have you tried running the linter with a downgraded yargs in web-ext and seeing if their tests start passing?

I'm running web-ext tests with a 0.15.7 addon-linter with a downgraded yargs and the web-ext tests are still failing. Investigating to see what else changed that might impact this.

**Comment by tofumatt** [comment]
Thanks; I didn’t get the chance to test it yet, but I’ll skip that now. 👍🏻

**Comment by muffinresearch** [comment]
I'm going to close this PR since I don't think this is the answer. Running web-ext lint with a version of web-ext where the tests are failing, `web-ext lint --source-dir [SOURCE]` runs correctly so I think this might be an issue with how the cli tests in web-ext are being run and less a bug in addons-linter.

**Pull request closed without merging**
