### PR TITLE
WIP: Added warning about unknown manifest keys

### LINKED ISSUE #1074: Warn about unknown manifest keys
### Describe the problem and steps to reproduce it:

* Create an extension with manifest that has an unsupported key, such as `comands` instead of [commands](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands).
* Run the linter

### What happened?

It should warn you that the key is unknown.

### What did you expect to happen?

Nothing happened. The linter reported no errors, warnings, or notices.

### Anything else we should know?

Chrome warns you about it like this in the extension panel: 
screenshot 2016-12-14 15 47 02

### PR DESCRIPTION
**Pull request by Divya063**
Fixes #1074 
* [x] This PR relates to an existing open issue and there are no existing
      PRs open for the same issue.
* [x] Add `Fixes #ISSUENUM` at the top of your PR.
* [ ] Add a description of the the changes introduced in this PR.
* [ ] The change has been successfully run locally.
* [ ] Add tests to cover the changes added in this PR.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Hey, did you have time to dive more into `ajv` after our chat on IRC? Do you need any help to finish this up?

**Comment by Divya063** [comment]
@EnTeQuAk I tried adding "additionalProperties": false to manifest.json file but still  bin/addons-linter is still not generating any warnings

**Comment by EnTeQuAk** [comment]
Hmm, I haven't looked at this in-depth yet, I'll take a look at what's wrong with the integration this week. Sorry for the late follow-up!

**Comment by EnTeQuAk** [comment]
Hey @Divya063, I looked at this but I found it also hard to navigate through schema parsing library. In theory there should be some builtin support there.

Do you have any time to work on this any further?

**Comment by EnTeQuAk** [comment]
Closing due to inactivity for now. Please feel very free to pick this work up whenever you have the time to look at this again, we can reopen this PR anytime.

**Pull request closed without merging**
